environment:
  SIZE: 14
  NUM_AGENTS: 15
  OBSTACLE_DENSITY: 0.5
  FOV: 7
  WINDOW_SIZE: 3

training:
  OVERFIT_TEST: 0
  SIZE: 14
  NUM_AGENTS: 15
  OBSTACLE_DENSITY: 0.5
  FOV: 7
  WINDOW_SIZE: 3
  LAMBDA: 1
  N_ACTIONS: 2

  BATCH_SIZE: 8
  LR: 1e-4
  BUFFER_SIZE: 10000
  TRAIN_STEPS: 1e10
  

paths:
  data_dir: "data/"
  save_dir: "models/"
