# warehouse
warehouse:
  root: "results/"

  environment:
    NUM_AGENTS: 25
    FOV: 7
    WINDOW_SIZE: 3
  
  training:
    OVERFIT_TEST: 0
    LAMBDA: 1
    N_ACTIONS: 2

    BATCH_SIZE: 8
    LR: 1e-4
    BUFFER_SIZE: 10000
    TRAIN_STEPS: 1e10

  paths:
    results: "warehouse_1/"
    map_file: "maps/warehouse_1/grid_map.npy"
    heur_file: "maps/warehouse_1/heuristic.npy"
    goals_locs: "maps/warehouse_1/goal_options.npy"
    start_locs: "maps/warehouse_1/start_options.npy"

# random
random:
  root: "results/"

  environment:
    SIZE: None
    NUM_AGENTS: 20
    OBSTACLE_DENSITY: None
    FOV: 7
    WINDOW_SIZE: 3

  training:
    OVERFIT_TEST: 0
    LAMBDA: 1
    N_ACTIONS: 2

    BATCH_SIZE: 8
    LR: 1e-4
    BUFFER_SIZE: 10000
    TRAIN_STEPS: 1e10

  paths:
    results: "random_20/"
    map_file: "maps/random_20/grid_map.npy"
    heur_file: "maps/random_20/heuristic.npy"
    goals_locs: None
    start_locs: None


# overfit
overfit:
  root: "results/"

  environment:
    SIZE: 14
    NUM_AGENTS: 7
    OBSTACLE_DENSITY: 0.5
    FOV: 7
    WINDOW_SIZE: 3

  training:
    OVERFIT_TEST: 3
    LAMBDA: 1
    N_ACTIONS: 2

    BATCH_SIZE: 8
    LR: 1e-4
    BUFFER_SIZE: 10000
    TRAIN_STEPS: 1e10

  paths:
    results: "overfit/"
    saved_models: "q_net_model/overfit_models/"
    map_file: "maps/random_grid_map_1.npy"
    heur_file: "maps/heuristic_map.npy"


# test
test:
  root: "results/"

  environment:
    SIZE: 14
    NUM_AGENTS: 70
    OBSTACLE_DENSITY: 0.5
    FOV: 7
    WINDOW_SIZE: 3

  paths:
    results: "test/"
    map_file: "maps/warehouse_2/grid_map.npy"
    heur_file: "maps/warehouse_2/heuristic.npy"
    goal_options: "maps/warehouse_2/goal_options.npy"
    start_options: "maps/warehouse_2/start_options.npy"
    start_locs: "maps/warehouse_2/start_locs_70N.pkl"
    goal_locs: "maps/warehouse_2/goal_locs_70N.pkl"



# generate results
generate_results:
  root: "results/"
  subroot: "generate_results/"

  environment:
    SIZE: 14
    NUM_AGENTS: 36
    OBSTACLE_DENSITY: 0.5
    FOV: 7
    WINDOW_SIZE: 3

  maps:
    warehouse_1: "maps/warehouse_1/"
    warehouse_2: "maps/warehouse_2/"
    random_1: "maps/random_1/"
    random_20: "maps/random_20/"
    random_40: "maps/random_40/"
    random_60: "maps/random_60/"

  map_file: "grid_map.npy"
  heur_file: "heuristic.npy"
  goal_options: "goal_options.npy"
  start_options: "start_options.npy"
  start_locs: "start_locs_"
  goal_locs: "goal_locs_"
