warehouse_2:
  root: "results/"

  environment:
    NUM_AGENTS: 160
    WINDOW_SIZE: 20
    FOV: 81 # WINDOW_SIZE * 4 + 1
  
  training:
    N_ACTIONS: 3
    DEVICE: "cuda:1"
    BATCH_SIZE: 64
    LR: 1e-4
    EPOCHS: 100
    MODE: threeway

  paths:
    map_file: "maps/kiva.npy"